#NAME: Robert Geil
#EMAIL: rgeil@ucla.edu
#ID: 104916969

dist: my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
	tar -cf lab4a-104916969.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
clean:
	$(RM) lab4a-104916969.tar.gz